### ISSUE TITLE
Apple M1 Support

### ISSUE THREAD

**Issue by FIrgolitsch** [fiji/HDF5_Vibez#18]
Hi,

I've been trying to get this plugin working with Fiji on an M1 MacBook. While Fiji is running natively it seems that there are no native HDF5 libraries available for this plugin. Is there any chance that this will be updated in the future?

**Comment by mkitti** [comment]
@ctrueden , we will need an update to 19.04.1 to include M1 support without user intervention.

**Comment by FIrgolitsch** [comment]
Thanks for the update! Looking forward to the next release.

**Comment by mkitti** [comment]
If you want a preview, here is the prototype:

https://github.com/JaneliaSciComp/jhdf5/releases/tag/jhdf5-19.04.1_fatjar

**Comment by ctrueden** [comment]
Thanks @FIrgolitsch. But @mkitti: there is still more work to be done to make HDF5_Vibez support M1 natively, right? Don't we need a new base-18.09 library as well?

**Comment by mkitti** [comment]
> Thanks @FIrgolitsch. But @mkitti: there is still more work to be done to make HDF5_Vibez support M1 natively, right? Don't we need a new base-18.09 library as well?

I'm working on it. To be honest, I'm not sure what those other binaries do and if Vibez currently uses them at all.

**Comment by ctrueden** [comment]
Is HDF5_Vibez actually working for you in M1 mode on your system, @FIrgolitsch? Or did you close this issue aspirationally? 😄

**Comment by FIrgolitsch** [comment]
I have been working with HDF5 files with Fiji with a native JDK. So that's why I presumed that it was fixed now. The only issue I encounter is that I get a "java.lang.IllegalArgumentException: Size exceeds Integer.MAX_VALUE" exception when I drag and drop a file into Fiji. When I open it using File > Import > HDF5 it works fine.

**Comment by FIrgolitsch** [comment]
Here it is:

`java.lang.IllegalArgumentException: Size exceeds Integer.MAX_VALUE
	at java.base/sun.nio.ch.FileChannelImpl.map(FileChannelImpl.java:941)
	at org.scijava.text.DefaultTextService.open(DefaultTextService.java:66)
	at org.scijava.text.DefaultTextService.asHTML(DefaultTextService.java:75)
	at org.scijava.text.io.TextIOPlugin.open(TextIOPlugin.java:75)
	at org.scijava.text.io.TextIOPlugin.open(TextIOPlugin.java:49)
	at org.scijava.io.DefaultIOService.open(DefaultIOService.java:93)
	at org.scijava.io.DefaultIOService.open(DefaultIOService.java:68)
	at HandleExtraFileTypes.openImage(HandleExtraFileTypes.java:549)
	at HandleExtraFileTypes.run(HandleExtraFileTypes.java:97)
	at ij.IJ.runUserPlugIn(IJ.java:237)
	at ij.IJ.runPlugIn(IJ.java:203)
	at ij.IJ.runPlugIn(IJ.java:192)
	at ij.io.Opener.openWithHandleExtraFileTypes(Opener.java:555)
	at ij.io.Opener.openUsingHandleExtraFileTypes(Opener.java:407)
	at ij.io.Opener.openImage(Opener.java:386)
	at ij.io.Opener.openImage(Opener.java:241)
	at ij.io.Opener.open(Opener.java:104)
	at ij.io.Opener.openAndAddToRecent(Opener.java:310)
	at ij.plugin.DragAndDrop.openFile(DragAndDrop.java:194)
	at ij.plugin.DragAndDrop.run(DragAndDrop.java:160)
	at java.base/java.lang.Thread.run(Thread.java:829)
`

**Comment by ctrueden** [comment]
Ooh, same bug as [here](https://github.com/fiji/fiji/issues/303#issuecomment-1092808661). Not HDF5-specific, but rather something about the text readers trying to open things they shouldn't. I'll investigate next week.

**Comment by mkitti** [comment]
In case we do need sis-base support, here's the patch so far:
https://github.com/JaneliaSciComp/sis-base-java/compare/master...janelia/aarch64-macosx

I still need to figure how how HDF5 Vibez might use this.

**Comment by mkitti** [comment]
Apparently, there is a pure Java fallback:
https://github.com/JaneliaSciComp/sis-base-java/blob/45fbd3115ea1aea77b778293519d3a0e5cff1c57/source/java/ch/systemsx/cisd/base/convert/NativeData.java#L48

**Comment by mkitti** [comment]
libunix fallback mode:
https://github.com/JaneliaSciComp/sis-base-java/blob/45fbd3115ea1aea77b778293519d3a0e5cff1c57/source/java/ch/systemsx/cisd/base/unix/Unix.java#L69

**Comment by mkitti** [comment]
Here's a short Python script to create a HDF5 file that creates the `IllegalArgumentException` error above when dragged and dropped into FIJI:

```
conda create -n hdf5 -c conda-forge numpy h5py
```

```python
import numpy as np, h5py

with h5py.File("test.hdf5", "w") as h5f:
    h5f.create_dataset("test", data = np.zeros((2**27,2)))
```

**Comment by ctrueden** [comment]
Thanks @mkitti, that was super useful! I was able to reproduce the problem, and fix the bug:

https://github.com/scijava/scijava-common/commit/aa7fe2e241c9e5dcca2ffad7945475aca47dc72c
