### ISSUE TITLE
Plugin is not working on the Fiji 1.53t version

### ISSUE THREAD

**Issue by Mailfert** [fiji/HDF5_Vibez#19]
Dear all,
the lugin does not work on my latest FiJi version.
Could you help me please?
![Capture d’écran 2023-05-30 103221](https://github.com/fiji/HDF5_Vibez/assets/41197554/e77ebad1-d650-41ca-9665-d66698561632)

**Comment by mkitti** [comment]
The plugin seems to be an old version.

**Comment by ctrueden** [comment]
@mkitti Yes, but it may be that the current state of the Java-8 update site is not functional, due to skew in Fiji 2.9.0? I will be uploading the latest Fiji release (2.13.1) this week, and will look into this as part of my updates.

**Comment by ctrueden** [comment]
@mkitti This plugin was updated to use the newer JHDF5 19.04 API with 9385408947bb00245cf5107e84ca772c10423950, which happened about 9 months ago. That change became part of HDF5_Vibez v1.1.1, which is part of Fiji 2.9.0, and is currently shipped on the Java-8 update site.

@Mailfert Is your Fiji up-to-date? Try running _Help &rarr; Update..._ and installing the latest updates. You should have HDF5_Vibez 1.1.1 or newer in your plugins folder; if not, that would explain the error you are seeing.

**Comment by peterhpark** [comment]
I have the same issue with the latest fiji. Both my Fiji and the plug-in were updated to the latest versions... Any solutions? 

<img width="830" alt="Screenshot 2024-07-05 at 17 03 08" src="https://github.com/fiji/HDF5_Vibez/assets/62927588/aff28077-3426-4a92-a7b0-82269bbbaeee">

**Comment by shiaway** [comment]
Is there any solution to this yet? I am also getting the same issue with version 2.16.0:

(Fiji Is Just) ImageJ 2.16.0/1.54g; Java 1.8.0_322 [64-bit]; Mac OS X 10.16; 94MB of 7221MB (1%)
 
java.lang.NoClassDefFoundError: ncsa/hdf/hdf5lib/exceptions/HDF5Exception
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at ij.IJ.runUserPlugIn(IJ.java:242)
	at ij.IJ.runPlugIn(IJ.java:210)
	at ij.Executer.runCommand(Executer.java:152)
	at ij.Executer.run(Executer.java:70)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: ncsa.hdf.hdf5lib.exceptions.HDF5Exception
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 9 more

**Comment by mkitti** [comment]
HDF5 Vibez 1.1.1 depends on jhdf5 19.04 as of this commit https://github.com/fiji/HDF5_Vibez/commit/9385408947bb00245cf5107e84ca772c10423950

These should now refer to `hdf.hdf5lib.exceptions.HDF5Exception` and not NCSA.
https://sissource.ethz.ch/sispub/jhdf5/-/blob/master/source/java/hdf/hdf5lib/exceptions/HDF5Exception.java?ref_type=heads

There must be an old copy somewhere. If you cannot find it, I suggest downloading a new copy of FIJI from https://fiji.sc/ .

**Comment by mkitti** [comment]
In the Fiji.app folder there should be a `plugins/HDF5_Vibez-1.1.1.jar` file. That should be the only one version of HDF_Vibez there.

**Comment by mkitti** [comment]
Also in the Fiji.app folder there should be `jars/jhdf5-19.04.1.jar`

If you have the `jar` command available, you can inspect that it refers to 
```
% jar tvf jhdf5-19.04.1.jar | grep HDF5Exception.class
   594 Mon Jul 25 20:49:22 EDT 2022 hdf/hdf5lib/exceptions/HDF5Exception.class
```

If you have the `unzip` command available, you can also do a similar inspection.

```
% unzip -l jhdf5-19.04.1.jar | grep HDF5Exception.class
      594  07-25-2022 20:49   hdf/hdf5lib/exceptions/HDF5Exception.class
```
