### ISSUE TITLE
Saving multi-channel TIF results in java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by bjtho08** [fiji/HDF5_Vibez#9]
I have not been able to do any debugging myself (I'm very new to programming and I mainly work with Python), so I don't know what exactly is causing this error. I'm running all the latest updates on an ubuntu 16.04 machine. Please let me know any necessary info I have left out.

**Comment by imagejan** [comment]
Hi @bjtho08, could you please post the exact steps you followed to get this exception? Also, the complete stack trace would surely be helpful to track this issue down. See [bug reporting best practices](https://imagej.net/Bug_reporting_best_practices).

**Comment by bjtho08** [comment]
> Hi @bjtho08, could you please post the exact steps you followed to get this exception? Also, the complete stack trace would surely be helpful to track this issue down. See [bug reporting best practices](https://imagej.net/Bug_reporting_best_practices).

Hi @imagejan, thanks for replying!
Steps to reproduce error:

1. On Ubuntu 16.04 open FIJI with HDF5 plugin installed
2. Install any updates and restart FIJI
3. Create a new multi-channel hyperstack
4. Open File menu -> Save As -> HDF5 (new or replace) ...
5. Choose default settings and click Save
This results in
```
Error while saving '/path/to/file.h5':
java.lang.ArrayIndexOutOfBoundsException
```
I have attached the dump stack from the moment of the error message on screen.

It works just fine on Windows 10, btw.
[fiji dump stack.txt](https://github.com/fiji/HDF5_Vibez/files/2557682/fiji.dump.stack.txt)

**Comment by bjtho08** [comment]
Update: It turns out that it does not work on my windows 10, either. unless it is a newly created empty multi-channel image. Trying to save an existing multi-channel image results in the above error.

**Comment by rejsmont** [comment]
Hi @bjtho08,

I could not reproduce your issue. Could you please provide the exact parameters of the image you are trying to save (x, y, z, c, t dimensions), axis order of your hyperstack, as well as options that you have selected for saving? Could you please also provide Fiji info?

`Plugins -> Debug -> System information`

Thanks!

Radek

**Comment by rejsmont** [comment]
Also, you seem to call HDF5 saver from within a script. Could we please take a look at your code?

**Comment by bjtho08** [comment]
So, I tested in on my co-worker's computer and his is working fine. So at the moment the error is on two different computers with different OS'es, but apparently it is very localized.

For the new hyperstack image, the parameters are as follows:
(400, 300, 1, 3, 1) 8-bit
For some unknown reason, it works on my windows 10 machine if I create it as 32-bit, but 8-bit fails consistently.
When saving I use no compression and the preset named Standard (no time).
The output log contains the following two lines after it failed:
`source level = 0
stackIndex = 1
`
I am not calling it from a script right now, so I don't have any code to show.
[ij-info.txt](https://github.com/fiji/HDF5_Vibez/files/2629358/ij-info.txt)

**Comment by rejsmont** [comment]
Hi @bjtho08,

Could you please check what java versions you have on machines where it works vs those where it does not?

Thanks

**Comment by bjtho08** [comment]
The problem turned out to be because I was using the HDF5 update site which took priority over the version from java-8. Now, however, I have another problem. When I save a file as HDF5, I am unable to open it again. I get the following error log:

```
loci.formats.UnknownFormatException: Unknown file format: C:\Users\bjarnet\Pictures\test.h5
	at loci.formats.ImageReader.getReader(ImageReader.java:197)
	at loci.plugins.in.ImportProcess.createBaseReader(ImportProcess.java:620)
	at loci.plugins.in.ImportProcess.initializeReader(ImportProcess.java:485)
	at loci.plugins.in.ImportProcess.execute(ImportProcess.java:138)
	at loci.plugins.in.Importer.showDialogs(Importer.java:140)
	at loci.plugins.in.Importer.run(Importer.java:76)
	at loci.plugins.LociImporter.run(LociImporter.java:78)
	at ij.IJ.runUserPlugIn(IJ.java:228)
	at ij.IJ.runPlugIn(IJ.java:192)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
```
This is a standard 3-channel TIF image saved in HDF5 and then I attempt to open the newly created .h5 file. Is there some obvious solution or should I submit a new issue?
